### PR TITLE
fix(app): resolving properly anchor links when using base-href

### LINKED ISSUE #216: [Bug] Documentation deployed with base href incorrectly resolves api routes
### Is this a regression?

I don't know

### Description

If you run application with documentation with `--base-href`, then API Reference routes are not created correctly - the base url is added twice to the url:

image

As you can see at the screenshot, `/some/base/href/` is added twice. For pages/categories etc. everything works fine, the issue is visible only with api keywords (links to api reference).

I've prepared a simple bug demo from this repository: [base-href-breaks-api-routes](https://github.com/AdrianKokot/ng-doc/tree/bug-demo/base-href-breaks-api-routes), if you run `npm run bug` and navigate to any api reference and then hover other api keyword you'll see wrong url.

Probably related to the URL parsing inside NgDocPageLinkComponent, because components receives URL without base href:
image

### Please provide the exception or error you saw

_No response_

### OS

Windows

### Browser

Chrome

### Node version

20.14.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AdrianKokot**
Resolves #216

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number

Issue Number: #216

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AdrianKokot** [comment]
Same as in #215, didn't write tests as I couldn't manage to change jest configuration to make them run.

**Review by skoropadas — APPROVED** [review]
Can't remember why I decided to use anchor tag for that, but anyways everything works fine and looks even better, thanks again!

**Comment by skoropadas** [comment]
No worries about tests, I'll set up them later

**Pull request merged**
